import type { Post } from "./types.ts";

export const seedPosts: Post[] = [
  {
    id: "the-quiet-art-of-paying-attention", title: "The quiet art of paying attention", category: "Perspectives", cover: "stillness", author: "Maya Sen", date: "2026-10-08T08:00:00Z", status: "published", owned: false, likes: 124,
    excerpt: "In a world that asks us to do more, what if the most interesting thing we could do was notice?",
    body: "The first thing I noticed was the light. Not a spectacular sunset, not the kind you stop to photograph. Just a thin rectangle of afternoon sun resting on the kitchen floor. It had probably been there every day. I had simply never been there with it.\n\nWe are very good at moving through our lives. We are less practiced at being in them. Between the next notification and the next thing to finish, attention becomes something we spend rather than something we choose.\n\n## Begin with something small\n\nThere is no elaborate routine required. Look at the street you already walk down. Listen to the end of someone's sentence without planning your response. Make a cup of tea and actually taste it.\n\nThe point is not to make ordinary life extraordinary. The point is to give ordinary life a chance to show you what it already contains.\n\n> Attention is a way of saying: this moment is worth something.\n\n## The space between things\n\nI used to fill every gap. Podcasts while cooking. Messages while waiting. Music on the walk to buy groceries. None of these are bad, but together they left no room for a thought to arrive uninvited.\n\nSo I began leaving one walk a day unfilled. On the first day, it was awkward. On the third, I noticed a tree I had walked past for two years. By the second week, the walk had become the part of the day I looked forward to.\n\n## A practice, not a performance\n\nYou will forget. You will spend an afternoon scrolling. You will miss the light on the kitchen floor. That is fine. Paying attention is not another thing to be good at. It is a place you can come back to.\n\nTry this tomorrow: before looking at your phone, look out of a window. Stay for ten breaths. Let the world be the first thing you meet.",
  },
  {
    id: "design-that-gets-out-of-the-way", title: "Good design knows when to get out of the way", category: "Design", cover: "shapes", author: "Arjun Rao", date: "2026-10-07T09:00:00Z", status: "published", owned: false, likes: 89,
    excerpt: "A case for fewer decisions, clearer interfaces, and a little more breathing room.",
    body: "A door handle should not need a tutorial. Neither should the button that saves your work. Yet we have become comfortable with interfaces that ask people to figure out what their designers meant.\n\n## Clarity is a creative choice\n\nMinimal design is often described as removing things. I think it is more useful to describe it as deciding what matters. A page with three buttons can still be confusing if all three compete for attention.\n\nStart with the task. What did someone come here to do? What information do they need before taking the next step? What can wait?\n\n## Make the important thing obvious\n\n- Give the primary action a clear name.\n- Group information by what people need, not by how the database stores it.\n- Use space to explain relationships.\n- Let errors explain how to recover.\n\nA quiet interface is not an empty interface. It is one in which the decisions have been made thoughtfully.\n\n## The best compliment\n\nWhen someone finishes a task and barely notices the interface, that can feel disappointing to a designer. We want people to notice our work. But sometimes the most thoughtful thing we can build is an experience that gives someone their attention back.",
  },
  {
    id: "a-smaller-internet", title: "What if we built a smaller internet?", category: "Technology", cover: "code", author: "Nikhil Mehta", date: "2026-10-06T10:00:00Z", status: "published", owned: false, likes: 76,
    excerpt: "Personal websites, tiny communities, and the joy of making something just because.",
    body: "My favorite corner of the internet has seventeen readers. It is a newsletter about repairing old cameras, written by someone who clearly enjoys both cameras and writing. There is no growth strategy. There is just care.\n\n## The web we can make\n\nThe internet is not only the large platforms we visit. It is also the little things we can build: a page for a local club, a collection of recipes, a map of places to sit and read.\n\nSmall projects give us room to experiment. We can choose a strange color. We can write for a specific person. We can decide that a site has done its job when it helps one friend.\n\n## Start with a real need\n\nBefore choosing a framework, choose someone to help. Ask what is frustrating them. Build the smallest useful version. Watch them use it.\n\nA finished, modest project teaches more than an ambitious project that never leaves a folder. It teaches you about forms, empty states, deployment, and the small differences between what you intended and what someone understood.\n\n## Leave room for personality\n\nEfficiency is useful. So is delight. The web had room for both when people treated their pages as places rather than products. It still does. We just have to make them.",
  },
  {
    id: "the-books-we-keep", title: "The books we keep, and the people we become", category: "Culture", cover: "sunset", author: "Leela Kapoor", date: "2026-10-05T08:00:00Z", status: "published", owned: false, likes: 63,
    excerpt: "Somewhere between a pencilled note and a folded corner, a book becomes a piece of us.",
    body: "There is a novel on my shelf that I have not read in eight years. I can still tell you which page has the coffee stain. I can tell you where I lived when I bought it and who recommended it.\n\n## More than a collection\n\nBooks are strangely good at keeping time. A receipt used as a bookmark can return you to an entire afternoon. A sentence underlined by a younger version of yourself can make you smile or wince.\n\nI used to think keeping books was about remembering what they said. Now I think it is also about remembering who we were when we read them.\n\n## Read without a finish line\n\nNot every book needs to be finished. Not every reading year needs a number. Sometimes ten pages that change how you see something are enough.\n\n> A bookshelf is a conversation between different versions of yourself.\n\nPick up something you loved a long time ago. Read a page at random. Notice what still speaks to you, and what no longer does. Both are a kind of discovery.",
  },
  {
    id: "take-the-long-way-home", title: "Take the long way home", category: "Travel", cover: "landscape", author: "Riya Das", date: "2026-10-04T11:00:00Z", status: "published", owned: false, likes: 98,
    excerpt: "You do not have to cross an ocean to find a place you have never been.",
    body: "I took a different turn on the way home and found a little courtyard with a tea stall. It was less than a kilometer from my apartment. I had lived nearby for three years.\n\n## Curiosity is a direction\n\nTravel is often framed as distance: how far we went, how many places we reached. But the part I love is the change in attention. In a new place, you notice the signs, the sounds, the way people stand at a crossing.\n\nYou can practice that at home. Take a bus to the end of its route. Visit a market before the shops open. Walk down the street you always pass.\n\n## A small field guide\n\n- Choose a familiar destination and an unfamiliar route.\n- Leave enough time to stop.\n- Carry a notebook rather than a checklist.\n- Ask someone about a place they love nearby.\n\n## Bring something back\n\nIt does not need to be a souvenir. A story, a new favorite bench, the name of a tree. The best part of a small adventure is that it makes the place you already live feel a little larger.",
  },
  {
    id: "make-room-for-play", title: "Make room for a little more play", category: "Perspectives", cover: "play", author: "Maya Sen", date: "2026-10-03T08:00:00Z", status: "published", owned: false, likes: 51,
    excerpt: "Not everything you make needs to be useful. Some things can simply make you happy.",
    body: "Last weekend I made a very bad drawing of a very good dog. It took twenty minutes. I did not post it. I did not improve it. I put it on the fridge.\n\n## Permission to be a beginner\n\nWe tend to turn interests into goals quickly. A sketch becomes a daily challenge. A walk becomes a step target. A new recipe becomes a project to perfect.\n\nGoals have their place. So does doing something without knowing whether you will be good at it.\n\n## A little experiment\n\nChoose something you can do in twenty minutes. Fold paper. Write a short story with an unlikely ending. Photograph things that are the same color. Make a playlist for an imaginary train journey.\n\nKeep the result, or do not. The result is not the reason. The point is to spend a little time making choices because you enjoy them.\n\nThe drawing is still on my fridge. The dog looks like a potato with ears. It makes me happy every morning.",
  },
  {
    id: "learning-to-build-in-public", title: "The first version is allowed to be ordinary", category: "Technology", cover: "shapes", author: "Arjun Rao", date: "2026-10-02T09:00:00Z", status: "published", owned: false, likes: 44,
    excerpt: "Why small, finished projects are the most underrated way to learn development.",
    body: "I spent a month choosing the perfect stack for a project that took a weekend to build. Looking back, the hardest part was not the code. It was being willing to make something smaller than the idea in my head.\n\n## Build the whole loop\n\nA project does not need many features to be useful practice. It does need a complete loop. Someone should be able to arrive, understand what to do, do it, and know it worked.\n\nFor a notes app, that means creating a note, finding it later, editing it, and handling the moment when there are no notes at all.\n\n## Learn from the edges\n\nThe interesting work often lives outside the happy path. What happens when the title is empty? When storage is unavailable? When the screen is narrow?\n\nAnswering these questions turns a demo into an experience. It also teaches you to see your code from someone else's point of view.\n\nStart with an ordinary first version. Finish it. Then let what you learn tell you what to build next.",
  },
];
